name: DT-flood

channels:
  - conda-forge
  - numba

dependencies:
  - cartopy
  - cwltool
  - ipykernel
  - hydromt_wflow
  - python<3.12
  - pip
  - pip: 
    - jupyter
    - git+https://github.com/Deltares-research/FloodAdapt.git@6a18711
    - gwwapi